//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impresso_Expresso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikli
    {
        public Artikli()
        {
            this.StavkeNarudzbes = new HashSet<StavkeNarudzbe>();
            this.StavkePrimkes = new HashSet<StavkePrimke>();
        }
    
        public int ID { get; set; }
        public int KategorijaID { get; set; }
        public string Naziv { get; set; }
        public decimal Cijena { get; set; }
        public double StanjeNaSkladistu { get; set; }
    
        public virtual Kategorije Kategorije { get; set; }
        public virtual ICollection<StavkeNarudzbe> StavkeNarudzbes { get; set; }
        public virtual ICollection<StavkePrimke> StavkePrimkes { get; set; }
    }
}
