//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impresso_Expresso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izvjestaji
    {
        public int ID { get; set; }
        public System.DateTime Datum { get; set; }
        public decimal PrometBlagajne { get; set; }
        public decimal PologUBlagajni { get; set; }
        public decimal GotovinaUBlagajni { get; set; }
        public int KonobarID { get; set; }
        public decimal IznosKartica { get; set; }
    }
}
