//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impresso_Expresso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbe
    {
        public Narudzbe()
        {
            this.StavkeNarudzbes = new HashSet<StavkeNarudzbe>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RacunID { get; set; }
        public int StolID { get; set; }
        public int KorisnikID { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Racuni Racuni { get; set; }
        public virtual Stolovi Stolovi { get; set; }
        public virtual ICollection<StavkeNarudzbe> StavkeNarudzbes { get; set; }
    }
}
