//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impresso_Expresso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Primke
    {
        public Primke()
        {
            this.StavkePrimkes = new HashSet<StavkePrimke>();
        }
    
        public int ID { get; set; }
        public int DobavljacID { get; set; }
        public int KorisnikID { get; set; }
        public System.DateTime DatumIVrijeme { get; set; }
    
        public virtual Dobavljaci Dobavljaci { get; set; }
        public virtual Korisnici Korisnici { get; set; }
        public virtual ICollection<StavkePrimke> StavkePrimkes { get; set; }
    }
}
