//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impresso_Expresso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transakcije
    {
        public int ID { get; set; }
        public Nullable<int> KasaID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public int TipID { get; set; }
        public decimal Iznos { get; set; }
    
        public virtual Kase Kase { get; set; }
        public virtual Tipovi Tipovi { get; set; }
    }
}
